"""
Django settings for inwonercentraal project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:  # Keep Django runnable before optional packages are installed.
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b)6p%%hys(^365l+f)actclgt8x&eab6^7yg!4mkzg#a27&0r1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reconciliation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inwonercentraal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inwonercentraal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MOCK_CAK_BASE_URL = os.getenv('MOCK_CAK_BASE_URL', 'http://127.0.0.1:8001')
MOCK_RDW_BASE_URL = os.getenv('MOCK_RDW_BASE_URL', 'http://127.0.0.1:8002')
MOCK_SVB_BASE_URL = os.getenv('MOCK_SVB_BASE_URL', 'http://127.0.0.1:8003')
MOCK_API_TIMEOUT_SECONDS = float(os.getenv('MOCK_API_TIMEOUT_SECONDS', '2'))
GREENPT_TIMEOUT_SECONDS = float(os.getenv('GREENPT_TIMEOUT_SECONDS', '10'))
INTAKE_DISCOVERY_MODEL = (
    os.getenv('INTAKE_DISCOVERY_MODEL')
    or os.getenv('OPENAI_MODEL')
    or ('gemma4' if os.getenv('GREENPT_API_KEY') and not os.getenv('OPENAI_API_KEY') else 'gpt-4.1-mini')
)
INTAKE_DISCOVERY_BASE_URL = os.getenv('INTAKE_DISCOVERY_BASE_URL') or os.getenv('OPENAI_BASE_URL')
INTAKE_DISCOVERY_TIMEOUT_SECONDS = float(os.getenv('INTAKE_DISCOVERY_TIMEOUT_SECONDS', '60'))

DEMO_DECEASED_BSN = os.getenv('DEMO_DECEASED_BSN', '111222333')
DEMO_DECEASED_NAME = os.getenv('DEMO_DECEASED_NAME', 'Cees de Vries')
DEMO_SURVIVING_PARTNER_BSN = os.getenv('DEMO_SURVIVING_PARTNER_BSN', '999888777')
DEMO_SURVIVING_PARTNER_NAME = os.getenv('DEMO_SURVIVING_PARTNER_NAME', 'Truus de Vries')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'reconciliation': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
